/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import com.mysql.jdbc.Connection;
import conexionSQL.conexionSQL;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.PrintJob;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileInputStream;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JEFFERSON
 */
public class Identificacion_Vehiculo extends javax.swing.JFrame {

        conexionSQL cc = new conexionSQL();
       Connection con = cc.conexion();
    /**
     * Creates new form Identificacion_Vehiculo
     */
    public Identificacion_Vehiculo() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(getBackground());
        mostrarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnPrincipal = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtplaca = new javax.swing.JTextField();
        txtnumero_motor = new javax.swing.JTextField();
        txtpoliza = new javax.swing.JTextField();
        txtnumero_chasis = new javax.swing.JTextField();
        txtnumero_copia_placa = new javax.swing.JTextField();
        txtbusqueda = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_Identificacion = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabelFotoA = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        txtfoto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPrincipal.setText("MENU PRINCIPAL");
        jPanel1.add(btnPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 450, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial Black", 2, 14)); // NOI18N
        jLabel10.setText("IDENTIFICACION VEHICULO");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        jLabel11.setText("PLACA");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 40, -1));

        jLabel12.setText("NUMERO MOTOR");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel13.setText("POLIZA");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, -1, -1));

        jLabel14.setText("NUMERO CHASIS");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, -1, -1));

        jLabel15.setText("NUMERO COPIA DE PLACA");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, -1, -1));

        jLabel16.setText("BUSQUEDA:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));
        jPanel1.add(txtplaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 130, -1));
        jPanel1.add(txtnumero_motor, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 160, 130, -1));
        jPanel1.add(txtpoliza, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 120, -1));
        jPanel1.add(txtnumero_chasis, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 110, -1));
        jPanel1.add(txtnumero_copia_placa, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 110, -1));

        txtbusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbusquedaActionPerformed(evt);
            }
        });
        jPanel1.add(txtbusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 210, -1));

        Tabla_Identificacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        Tabla_Identificacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabla_IdentificacionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla_Identificacion);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 620, 170));

        jButton1.setText("SUBIR FOTO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, -1, -1));
        jPanel1.add(jLabelFotoA, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 160, 130));

        btnNuevo.setText("NUEVO");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, -1));

        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 450, 100, -1));

        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, -1, -1));

        btnActualizar.setText("ACTUALIZAR");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 450, -1, -1));
        jPanel1.add(txtfoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 130, -1));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 650, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Tabla_IdentificacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabla_IdentificacionMouseClicked
        // TODO add your handling code here:
           int filaSeleccionada = Tabla_Identificacion.rowAtPoint(evt.getPoint());
        txtplaca.setText(Tabla_Identificacion.getValueAt(filaSeleccionada, 0).toString());
        txtpoliza.setText(Tabla_Identificacion.getValueAt(filaSeleccionada, 2).toString());
        txtnumero_copia_placa.setText(Tabla_Identificacion.getValueAt(filaSeleccionada, 3).toString());
        txtnumero_motor.setText(Tabla_Identificacion.getValueAt(filaSeleccionada, 4).toString());
        txtnumero_chasis.setText(Tabla_Identificacion.getValueAt(filaSeleccionada, 5).toString());
        jLabelFotoA.setText(Tabla_Identificacion.getValueAt(filaSeleccionada, 6).toString());
    
    }//GEN-LAST:event_Tabla_IdentificacionMouseClicked

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
         limpiarCajas();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
         insertarDatos();
         limpiarCajas();
         mostrarDatos();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        eliminarRegistros();
        limpiarCajas();
        mostrarDatos();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        actualizarDatos();
        limpiarCajas();
        mostrarDatos();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void txtbusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbusquedaActionPerformed
        // TODO add your handling code here:
        filtrarDatos(txtbusqueda.getText());
    }//GEN-LAST:event_txtbusquedaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        File archivo;
        JFileChooser flcAbritArchivo=new JFileChooser();
        flcAbritArchivo.setFileFilter(new FileNameExtensionFilter("archivo de imagen", "jpg", "jpeg"));
        int respuesta=flcAbritArchivo.showOpenDialog(this);
        
        if(respuesta==JFileChooser.APPROVE_OPTION){
            
            archivo=flcAbritArchivo.getSelectedFile();
            txtfoto.setText(archivo.getAbsolutePath());
            Image foto=getToolkit().getImage(txtfoto.getText());
            foto=foto.getScaledInstance(160, 130, 1);
            jLabelFotoA.setIcon(new ImageIcon(foto));
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public void limpiarCajas() {
        txtplaca.setText("");
        txtpoliza.setText("");
        txtnumero_copia_placa.setText("");
        txtnumero_motor.setText("");
        txtnumero_chasis.setText("");
        jLabelFotoA.setIcon(null);
    }
    
    
            public void mostrarDatos() {
        String[] titulos = {"PLACA", "REGISTRO_TECNICO", "POLIZA", "NUMERO COPIA PLACA", "MOTOR", "CHASIS", "FOTO"};
        String[] registros = new String[8];
        DefaultTableModel modelo = new DefaultTableModel(null, titulos);
        String SQL = "select * from tb_identificacion_vehiculo";
        try {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(SQL);

            while (rs.next()) {
                //PARTE DE  LA BASE DE DATOS MYSQL
                registros[0] = rs.getString("placa_iv");
                registros[1] = rs.getString("reg_datos_tec");
                registros[2] = rs.getString("poliza");
                registros[3] = rs.getString("nro_copia_placa_tpa");
                registros[4] = rs.getString("nro_motor");
                registros[5] = rs.getString("nro_chasis");
                registros[6] = rs.getString("foto");
                modelo.addRow(registros);
            }
            Tabla_Identificacion.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "MOSTRAR DATOS ERROR" + e.getMessage());
        }
        }
            
            
    public void insertarDatos() {
            FileInputStream archivoFoto;
            File nombreFoto;
        try {
            String SQL = "insert into tb_identificacion_vehiculo(placa_iv,poliza,nro_copia_placa_tpa,nro_motor,nro_chasis,foto)values (?,?,?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(SQL);
          //  pst.setString(0, txtci.getText());
            nombreFoto=new File (txtfoto.getText());
            archivoFoto=new FileInputStream(nombreFoto);
            
            pst.setString(1, txtplaca.getText());
            pst.setString(3, txtpoliza.getText());
            pst.setString(4, txtnumero_copia_placa.getText());
            pst.setString(5, txtnumero_motor.getText());
            pst.setString(6, txtnumero_chasis.getText());
            pst.setBinaryStream(7, archivoFoto,archivoFoto.available());
            pst.execute();
            JOptionPane.showMessageDialog(null, "Registro Exitoso");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Registro ERROR" + e.getMessage());
        }
        }
                
                
               public void actualizarDatos() {
        try {
            String SQL = "update tb_identificacion_vehiculo set poliza=?,nro:copia_placa_tpa=?,nro_motor=?,nro_chasis=?,foto=? where placa_iv=? reg_datos_tec=?"; //where idalumnos=?
            int filaSeleccionado = Tabla_Identificacion.getSelectedRow();
            String dao = (String) Tabla_Identificacion.getValueAt(filaSeleccionado, 0);
            PreparedStatement pst = con.prepareStatement(SQL);

           // pst.setString(1, txtplaca.getText());
            pst.setString(3, txtpoliza.getText());
            pst.setString(4, txtnumero_copia_placa.getText());
            pst.setString(5, txtnumero_motor.getText());
            pst.setString(6, txtnumero_chasis.getText());
            pst.setString(7, jLabelFotoA.getText());
            pst.setString(8, dao);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Registro Editado Exitoso");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Registro Editado ERROR" + e.getMessage());
        }
    }
               
         public void eliminarRegistros() {
        int filaSeleccionada = Tabla_Identificacion.getSelectedRow();
        try {
            String SQL = "delete from tb_identificacion_vehiculo where placa_iv=" + Tabla_Identificacion.getValueAt(filaSeleccionada, 0);
            Statement st = con.createStatement();
            int n = st.executeUpdate(SQL);
            if (n > 0) {
                JOptionPane.showMessageDialog(null, "Registro ELIMINADO");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Eliminar Registro ERROR" + e.getMessage());
        }
        }
      
              public void filtrarDatos(String valor) {
        String[] titulos = {"PLACA", "REGISTRO_TECNICO", "POLIZA", "NUMERO COPIA PLACA", "MOTOR", "CHASIS", "FOTO"};
        String[] registros = new String[8];
        DefaultTableModel modelo = new DefaultTableModel(null, titulos);
        String SQL = "select * from tb_identificacion_vehiculo where placa_iv like '%" + valor + "%'";
        try {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(SQL);

            while (rs.next()) {
                registros[0] = rs.getString("placa_iv");
                registros[1] = rs.getString("reg_datos_tec");
                registros[2] = rs.getString("poliza");
                registros[3] = rs.getString("nro_copia_placa_tpa");
                registros[4] = rs.getString("nro_motor");
                registros[5] = rs.getString("nro_chasis");
                registros[6] = rs.getString("foto");
                modelo.addRow(registros);
            }
            Tabla_Identificacion.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "MOSTRAR DATOS ERROR" + e.getMessage());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Identificacion_Vehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Identificacion_Vehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Identificacion_Vehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Identificacion_Vehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Identificacion_Vehiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla_Identificacion;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnPrincipal;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabelFotoA;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtbusqueda;
    private javax.swing.JTextField txtfoto;
    private javax.swing.JTextField txtnumero_chasis;
    private javax.swing.JTextField txtnumero_copia_placa;
    private javax.swing.JTextField txtnumero_motor;
    private javax.swing.JTextField txtplaca;
    private javax.swing.JTextField txtpoliza;
    // End of variables declaration//GEN-END:variables
}
